apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: \temp\kompose -f docker-compose.yml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: \temp\kompose -f docker-compose.yml convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: server
    spec:
      containers:
      - env:
        - name: FLASK_ENV
          value: development
        image: server
        imagePullPolicy: ""
        name: paws-compose-server
        ports:
        - containerPort: 5000
        resources: {}
        volumeMounts:
        - mountPath: /app/static/raw_data
          name: src-archive
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: src-archive
        persistentVolumeClaim:
          claimName: src-archive
status: {}
